server:
  port: 8082
  address: 0.0.0.0

spring:
  application:
    name: product-service
  jwt:
    secret: mysuperlongsecretkeythatissecureandlongenoughforjwttokengeneration1234567890
  datasource:
    url: jdbc:h2:file:./data/product_db;AUTO_SERVER=TRUE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    "[com.trace]": INFO
    "[org.springframework.web]": INFO
    "[org.hibernate.SQL]": DEBUG
  file:
    name: ../logs/product-service.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
